async 翻译完成了
iliakan/javascript-tutorial-cn pull request #18
Opened 2017-10-20 09:12 UTC by iammvp

2017-10-23 13:33 UTC, linhe0x0 requested changes
建议规范下文中的标点使用方法。具体请参考 [译文排版规则指北](https://github.com/xitu/gold-miner/wiki/%E8%AF%91%E6%96%87%E6%8E%92%E7%89%88%E8%A7%84%E5%88%99%E6%8C%87%E5%8C%97)

2017-10-23 13:33 UTC, linhe0x0 commented on .gitignore
> +6-async/03-promise-chaining/article.bak.md
为什么要加这些东西？

2017-10-23 13:33 UTC, linhe0x0 commented on 6-async/01-callbacks/article.md
> +Javascript 中的很多操作都是 *异步*。
[斜体文字使用加粗样式代替](https://github.com/xitu/gold-miner/wiki/%E8%AF%91%E6%96%87%E6%8E%92%E7%89%88%E8%A7%84%E5%88%99%E6%8C%87%E5%8C%97#%E6%96%9C%E4%BD%93%E6%96%87%E5%AD%97%E4%BD%BF%E7%94%A8%E5%8A%A0%E7%B2%97%E6%A0%B7%E5%BC%8F%E4%BB%A3%E6%9B%BF)

2017-10-23 13:33 UTC, linhe0x0 commented on 6-async/01-callbacks/article.md
> +// 加载然后执行新的Javascript文件
[中英文之间需要增加空格](https://github.com/xitu/gold-miner/wiki/%E8%AF%91%E6%96%87%E6%8E%92%E7%89%88%E8%A7%84%E5%88%99%E6%8C%87%E5%8C%97#%E4%B8%AD%E8%8B%B1%E6%96%87%E4%B9%8B%E9%97%B4%E9%9C%80%E8%A6%81%E5%A2%9E%E5%8A%A0%E7%A9%BA%E6%A0%BC)

2017-10-23 13:33 UTC, linhe0x0 commented on 6-async/01-callbacks/article.md
> +  alert( _ ); // _在刚才载入的文件中定义
多了一个下划线 😄

2017-10-23 13:33 UTC, linhe0x0 commented on 6-async/01-callbacks/article.md
> +用单个 `回掉` 函数来处理错误和成功。
『回掉』=>『回调』

2017-10-23 13:33 UTC, linhe0x0 commented on 6-async/01-callbacks/article.md
> +1. 载入 `1.js`，如果没有出错的话。
『如果没有出错的话。』=>『如果没有出错的话然后继续。』

2017-10-23 13:33 UTC, linhe0x0 commented on 6-async/01-callbacks/article.md
> +它确实解决了我们的一些问题，但是我们的代码却变得跟撕碎的excel表格似的。也许你已经察觉到了，它非常难以阅读。人们在阅读代码的时候需要去寻找所定义的函数在哪儿。这是非常不方便的，特别是当读者对代码不了解的时候，他们不知道去那儿找到对应的函数。
[中英文之间需要增加空格](https://github.com/xitu/gold-miner/wiki/%E8%AF%91%E6%96%87%E6%8E%92%E7%89%88%E8%A7%84%E5%88%99%E6%8C%87%E5%8C%97#%E4%B8%AD%E8%8B%B1%E6%96%87%E4%B9%8B%E9%97%B4%E9%9C%80%E8%A6%81%E5%A2%9E%E5%8A%A0%E7%A9%BA%E6%A0%BC)

2017-10-23 13:33 UTC, sqrthree commented on 6-async/01-callbacks/article.md
> +它确实解决了我们的一些问题，但是我们的代码却变得跟撕碎的excel表格似的。也许你已经察觉到了，它非常难以阅读。人们在阅读代码的时候需要去寻找所定义的函数在哪儿。这是非常不方便的，特别是当读者对代码不了解的时候，他们不知道去那儿找到对应的函数。
『去那儿』=>『去哪儿』

2017-10-23 13:33 UTC, sqrthree commented on 6-async/02-promise-basics/article.md
> +为了摆脱这无穷无尽的为什么, 你承诺只要歌曲一发售马上告诉他们. 你让粉丝们在一份表格上填写自己的名字和地址, 等到歌曲创作完成, 他们就马上可以知道啦. 如果出了什么意外, 歌曲永远不会发售的话, 粉丝也会得到这个消息.
[使用全角中文标点](https://github.com/xitu/gold-miner/wiki/%E8%AF%91%E6%96%87%E6%8E%92%E7%89%88%E8%A7%84%E5%88%99%E6%8C%87%E5%8C%97#%E4%BD%BF%E7%94%A8%E5%85%A8%E8%A7%92%E4%B8%AD%E6%96%87%E6%A0%87%E7%82%B9)

2017-10-23 13:33 UTC, sqrthree commented on 6-async/02-promise-basics/article.md
> +现在每个人都开心了: 你再也不会被粉丝纠缠了, 而你的粉丝们也不会错误你的下一首单曲.
『错误』=>『错过』

2017-10-23 13:33 UTC, sqrthree commented on 6-async/02-promise-basics/article.md
> +如果我们只关心执行成功的返回值的话, 我们可以值提供一个参数给 `.then`:
值提供？

2017-10-23 13:33 UTC, sqrthree commented on 6-async/03-promise-chaining/article.md
> +这让扩展计划任务变为可能。即时我们现在没有扩展链的计划，我们之后可能会需要它。
即时？

2017-10-23 13:33 UTC, sqrthree commented on 6-async/03-promise-chaining/article.md
> +这里的 `.catch` 正常完成。所以下一个成功的处理者被执行。或者它会返回一些东西，没什么却别。
却别？

2017-10-23 13:33 UTC, sqrthree commented on 6-async/03-promise-chaining/article.md
> +目前来说，不管服务器是挂了还是返回任何东西，我们的代码都会尝试将反应当做 JSON 对待。运行上面的代码你就会发现问题，因为 `no-such-user.json` 根本不存在。
『反应』=>『响应』

2017-10-23 13:33 UTC, sqrthree commented on 6-async/03-promise-chaining/article.md
> +2. 否则，如果发生了一个错误，我们会在检查它 `(2)` 。只有是 HTTP 错误并且状态是404的时候，我们会让用户再次输入。至于其他的错误 -- 我们不知道怎样处理他， 所以我们就重新抛出它。
注意统一『它』的用法。

2017-10-23 13:33 UTC, sqrthree commented on 6-async/03-promise-chaining/article.md
> +大部门的 JavaScript 引擎会追踪这种情况，然后生成一个全局的错误。我们可以在 console 中打印出来。
大部门？多大的部门？

2017-10-23 13:33 UTC, sqrthree commented on 6-async/03-promise-chaining/article.md
> +在像 Node.JS 这样的非浏览器环境下会有一些其他的类似的方法来追中没有被处理的错误。
追中？

2017-10-23 13:33 UTC, sqrthree commented on 6-async/03-promise-chaining/article.md
> +总而言之，`.then/catch(handler)` 会根据错误处理者的不用返回不用的新 promise：
不用返回不用？

2017-10-23 13:33 UTC, sqrthree commented on 6-async/05-async-await/article.md
> +使用 `async/await` 的时候，我们基本不需要写 `promise.then/catch`，但是我们任然不应该忘记它们是基于 promises，因为有时（e.g. 在最外层）我们不得不使用那些方法。同时， `Promise.all` 用来同时等待多个任务非常棒。
任然？

2017-10-24 03:06 UTC, iammvp commented on .gitignore
> +6-async/03-promise-chaining/article.bak.md
误操作，已恢复

2017-10-24 03:06 UTC, iammvp commented on 6-async/01-callbacks/article.md
> +Javascript 中的很多操作都是 *异步*。
已修改

2017-10-24 03:06 UTC, iammvp commented on 6-async/01-callbacks/article.md
> +// 加载然后执行新的Javascript文件
已修改

2017-10-24 03:06 UTC, iammvp commented on 6-async/01-callbacks/article.md
> +  alert( _ ); // _在刚才载入的文件中定义
已修改，其实我想表达的是 _ 这个函数是在刚才载入的文件中定义

2017-10-24 03:06 UTC, iammvp commented on 6-async/01-callbacks/article.md
> +用单个 `回掉` 函数来处理错误和成功。
已修改

2017-10-24 03:06 UTC, iammvp commented on 6-async/01-callbacks/article.md
> +1. 载入 `1.js`，如果没有出错的话。
已修改

2017-10-24 03:06 UTC, iammvp commented on 6-async/01-callbacks/article.md
> +它确实解决了我们的一些问题，但是我们的代码却变得跟撕碎的excel表格似的。也许你已经察觉到了，它非常难以阅读。人们在阅读代码的时候需要去寻找所定义的函数在哪儿。这是非常不方便的，特别是当读者对代码不了解的时候，他们不知道去那儿找到对应的函数。
已修改

2017-10-24 03:06 UTC, iammvp commented on 6-async/01-callbacks/article.md
> +它确实解决了我们的一些问题，但是我们的代码却变得跟撕碎的excel表格似的。也许你已经察觉到了，它非常难以阅读。人们在阅读代码的时候需要去寻找所定义的函数在哪儿。这是非常不方便的，特别是当读者对代码不了解的时候，他们不知道去那儿找到对应的函数。
已修改

2017-10-24 03:07 UTC, iammvp commented on 6-async/02-promise-basics/article.md
> +为了摆脱这无穷无尽的为什么, 你承诺只要歌曲一发售马上告诉他们. 你让粉丝们在一份表格上填写自己的名字和地址, 等到歌曲创作完成, 他们就马上可以知道啦. 如果出了什么意外, 歌曲永远不会发售的话, 粉丝也会得到这个消息.
已修改

2017-10-24 03:07 UTC, iammvp commented on 6-async/02-promise-basics/article.md
> +现在每个人都开心了: 你再也不会被粉丝纠缠了, 而你的粉丝们也不会错误你的下一首单曲.
已修改

2017-10-24 03:07 UTC, iammvp commented on 6-async/02-promise-basics/article.md
> +如果我们只关心执行成功的返回值的话, 我们可以值提供一个参数给 `.then`:
只提供

2017-10-24 03:07 UTC, iammvp commented on 6-async/03-promise-chaining/article.md
> +这让扩展计划任务变为可能。即时我们现在没有扩展链的计划，我们之后可能会需要它。
即使

2017-10-24 03:07 UTC, iammvp commented on 6-async/03-promise-chaining/article.md
> +这里的 `.catch` 正常完成。所以下一个成功的处理者被执行。或者它会返回一些东西，没什么却别。
区别

2017-10-24 03:07 UTC, iammvp commented on 6-async/03-promise-chaining/article.md
> +目前来说，不管服务器是挂了还是返回任何东西，我们的代码都会尝试将反应当做 JSON 对待。运行上面的代码你就会发现问题，因为 `no-such-user.json` 根本不存在。
已修改

2017-10-24 03:07 UTC, iammvp commented on 6-async/03-promise-chaining/article.md
> +2. 否则，如果发生了一个错误，我们会在检查它 `(2)` 。只有是 HTTP 错误并且状态是404的时候，我们会让用户再次输入。至于其他的错误 -- 我们不知道怎样处理他， 所以我们就重新抛出它。
已修改

2017-10-24 03:07 UTC, iammvp commented on 6-async/03-promise-chaining/article.md
> +大部门的 JavaScript 引擎会追踪这种情况，然后生成一个全局的错误。我们可以在 console 中打印出来。
大部分 😄

2017-10-24 03:07 UTC, iammvp commented on 6-async/03-promise-chaining/article.md
> +在像 Node.JS 这样的非浏览器环境下会有一些其他的类似的方法来追中没有被处理的错误。
追踪

2017-10-24 03:07 UTC, iammvp commented on 6-async/03-promise-chaining/article.md
> +总而言之，`.then/catch(handler)` 会根据错误处理者的不用返回不用的新 promise：
会根据错误处理者的不同返回不同的新 promise

2017-10-24 03:07 UTC, iammvp commented on 6-async/05-async-await/article.md
> +使用 `async/await` 的时候，我们基本不需要写 `promise.then/catch`，但是我们任然不应该忘记它们是基于 promises，因为有时（e.g. 在最外层）我们不得不使用那些方法。同时， `Promise.all` 用来同时等待多个任务非常棒。
仍然

2017-10-25 08:37 UTC, linhe0x0 approved these changes

2017-10-25 08:44 UTC, sqrthree commented
@iammvp LGTM. 有一个小问题哈~ 关于英文单词，翻译为中文之后还要保留复数形式吗？我倾向于保留单数形式，因为一般中文没有这种表达习惯。@ericyang89 @maoxiaoke 你们的意见呢？

2017-10-26 03:07 UTC, iammvp commented
@sqrthree 我是按照原文来写的,它是单数我就是单数,他是复数我就是复数. 可以按照你的习惯统一下.

2017-10-26 05:44 UTC, maoxiaoke commented
@sqrthree @iammvp 我觉得按照原文本意吧，如果复数更合理就采用复数。如果单、复都可以，我认为就使用单数

2017-11-22 14:53 UTC, merged