完成简介的翻译
iliakan/javascript-tutorial-cn pull request #20
Opened 2017-10-31 13:19 UTC by ericyang89

完成简介部分的翻译 。 
哪位大大来review一下，谢谢。

2017-10-31 13:19 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/iliakan/javascript-tutorial-cn?pullRequest=20) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/iliakan/javascript-tutorial-cn?pullRequest=20) before we can accept your contribution.<br/><hr/>**yangchuan** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/iliakan/javascript-tutorial-cn?pullRequest=20) it.</sub>

2017-11-02 06:47 UTC, linhe0x0 requested changes

2017-11-02 06:47 UTC, sqrthree commented on 1-js/01-getting-started/1-intro/article.md
> +*JavaScript* 最初的目的是为了 *"让网页动起来"*。
[斜体文字使用加粗样式代替](https://github.com/xitu/gold-miner/wiki/%E8%AF%91%E6%96%87%E6%8E%92%E7%89%88%E8%A7%84%E5%88%99%E6%8C%87%E5%8C%97#%E6%96%9C%E4%BD%93%E6%96%87%E5%AD%97%E4%BD%BF%E7%94%A8%E5%8A%A0%E7%B2%97%E6%A0%B7%E5%BC%8F%E4%BB%A3%E6%9B%BF)

2017-11-02 06:47 UTC, sqrthree commented on 1-js/01-getting-started/1-intro/article.md
> +这种编程语言我们称之为*脚本*。把它嵌入到HTML当中，在页面加载的时候会自动执行。
[中英文之间需要增加空格](https://github.com/xitu/gold-miner/wiki/%E8%AF%91%E6%96%87%E6%8E%92%E7%89%88%E8%A7%84%E5%88%99%E6%8C%87%E5%8C%97#%E4%B8%AD%E8%8B%B1%E6%96%87%E4%B9%8B%E9%97%B4%E9%9C%80%E8%A6%81%E5%A2%9E%E5%8A%A0%E7%A9%BA%E6%A0%BC)，下同。

2017-11-02 06:47 UTC, sqrthree commented on 1-js/01-getting-started/1-intro/article.md
> +上面这些经常在一些关于开发的文章中提到；也很方便记忆。比喻：某个新的功能，JavaScript引擎V8是支持的；那么我们可以认为这个功能在Chrome和Opera中可以正常运行。
『上面这些经常在一些关于开发的文章中提到；也很方便记忆。』=>『上面这些很容易记忆，因为经常出现在网上关于开发的文章中』我觉得保持原文的语序更合适一点吧。

2017-11-02 06:47 UTC, sqrthree commented on 1-js/01-getting-started/1-intro/article.md
> +上面这些经常在一些关于开发的文章中提到；也很方便记忆。比喻：某个新的功能，JavaScript引擎V8是支持的；那么我们可以认为这个功能在Chrome和Opera中可以正常运行。
『We'll use them too』没有翻译，导致不太方便理解下文。『For instance,』我觉得翻译成『例如』更合适一点。

2017-11-02 06:47 UTC, sqrthree commented on 1-js/01-getting-started/1-intro/article.md
> +- 向远处服务器发送请求，下载或上传文件（[AJAX](https://en.wikipedia.org/wiki/Ajax_(programming))和[COMET](https://en.wikipedia.org/wiki/Comet_(programming))技术）。
『远处服务器』=>『远程服务器』

2017-11-02 06:47 UTC, sqrthree commented on 1-js/01-getting-started/1-intro/article.md
> +- 不同的浏览器标签页基本彼此不相关。有时候，也会有一些关系。例如，通过JavaScript打开另外一个新的标签页。如果两个标签页打开的不是同一个网站，他们不能够相互通信（域名，协议或者端口任一不相同的网站，都认为是不同的网站）。
『域名，协议或者端口』=>『域名、协议或者端口』

2017-11-02 06:47 UTC, sqrthree commented on 1-js/01-getting-started/1-intro/article.md
>  Such limits do not exist if JavaScript is used outside of the browser, for example on a server. Modern browsers also allow installing plugin/extensions which may get extended permissions.
英文没有删除。

2017-11-02 06:47 UTC, sqrthree commented on 1-js/01-getting-started/1-intro/article.md
> +当然，学习一项新技术的时候，最好先看一下他的前景。所有，接下来，我们来看看新的趋势（包含一些新的语言）。
所有，接下来？

2017-11-02 06:47 UTC, sqrthree commented on 1-js/01-getting-started/1-intro/article.md
> +现代的工具编译得很快，并且让用户不可感知。这就允许开发中使用一种新的语言，就是使用JavaScript一样。
就是使用JavaScript一样？

2017-11-02 06:47 UTC, sqrthree commented on 1-js/01-getting-started/1-intro/article.md
> +- [TypeScript](http://www.typescriptlang.org/) 主要是是添加了严格类型系统。这样就能简化开发，也能用于开发一些负责的系统。TypeScript是微软开发的。
负责的系统？

2017-11-03 13:04 UTC, ericyang89 commented on 1-js/01-getting-started/1-intro/article.md
> +*JavaScript* 最初的目的是为了 *"让网页动起来"*。
你好  这个在markdown  我该怎么操作？ 怎么使用斜体代替粗体？

2017-11-03 13:26 UTC, ericyang89 commented on 1-js/01-getting-started/1-intro/article.md
> +*JavaScript* 最初的目的是为了 *"让网页动起来"*。
知道了  使用**粗体**。 而不是使用*斜体*

2017-11-07 15:13 UTC, linhe0x0 requested changes

2017-11-07 15:13 UTC, sqrthree commented on 1-js/01-getting-started/2-code-editors/article.md
> +“轻量编辑器”和 IDE 有很大的区别。IDE 一般是项目中使用，就意味着一开始要加载很多数据，并且在使用的过程中会分析项目的结构和内容。如果我们只需要编辑一个文件，那么“轻量编辑机”会更快的帮我们打开文件。
『编辑机』=>『编辑器』

2017-11-07 15:14 UTC, sqrthree commented on 1-js/01-getting-started/2-code-editors/article.md
> +“轻量编辑器”和 IDE 有很大的区别。IDE 一般是项目中使用，就意味着一开始要加载很多数据，并且在使用的过程中会分析项目的结构和内容。如果我们只需要编辑一个文件，那么“轻量编辑机”会更快的帮我们打开文件。
文中有几处英文前后没有加空格的地方，还望能够辛苦检查一下哈。

2017-12-03 12:58 UTC, ericyang89 commented
再看一下 还有哪些问题？

2017-12-07 02:48 UTC, linhe0x0 approved these changes

2017-12-07 02:49 UTC, sqrthree commented
LGTM

2017-12-16 15:02 UTC, merged