05-01-regexp-introduction
iliakan/javascript-tutorial-cn pull request #5
Opened 2017-08-27 04:39 UTC by bpceee

2017-09-11 13:06 UTC, ericyang89 commented
+ 建议  方法-->方式。    不然和其他的method不清楚；
> Regular expressions is a powerful way of searching and replacing inside a string.
 正则表达式是一种在字符串内进行搜索和替换的强大方法。
+131 行   字串-->字符串            
其他我觉得ok

2017-09-13 14:41 UTC, linhe0x0 requested changes

2017-09-13 14:41 UTC, sqrthree commented on 5-regular-expressions/01-regexp-introduction/article.md
> +要搜索一个字符串, 我们可以使用 [search](mdn:js/String/search) 方法。
[使用全角中文标点](https://github.com/xitu/gold-miner/wiki/%E8%AF%91%E6%96%87%E6%8E%92%E7%89%88%E8%A7%84%E5%88%99%E6%8C%87%E5%8C%97#%E4%BD%BF%E7%94%A8%E5%85%A8%E8%A7%92%E4%B8%AD%E6%96%87%E6%A0%87%E7%82%B9)

2017-09-13 14:41 UTC, sqrthree commented on 5-regular-expressions/01-regexp-introduction/article.md
> +- 一个正则表达式由一个模式和一些可选标志（`g`, `i`, `m`, `u`, `y`）组成。
『`g`, `i`, `m`, `u`, `y`』=>『`g`、`i`、`m`、`u`、`y`』

2017-10-30 14:04 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/iliakan/javascript-tutorial-cn?pullRequest=5) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/iliakan/javascript-tutorial-cn?pullRequest=5) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/iliakan/javascript-tutorial-cn?pullRequest=5) it.</sub>

2017-10-31 13:06 UTC, linhe0x0 approved these changes

2017-11-22 14:54 UTC, merged