2-2-01-introduction-browser-events
iliakan/javascript-tutorial-cn pull request #6
Opened 2017-09-08 07:44 UTC by edward9145

2017-09-13 14:56 UTC, linhe0x0 requested changes

2017-09-13 14:56 UTC, sqrthree commented on 2-ui/2-events/01-introduction-browser-events/article.md
> +*事件*是当某个交互产生时的信号。所有的 DOM 节点都会产生这样的信号（但事件的产生并不限于 DOM 节点）。
[斜体文字使用加粗样式代替](https://github.com/xitu/gold-miner/wiki/%E8%AF%91%E6%96%87%E6%8E%92%E7%89%88%E8%A7%84%E5%88%99%E6%8C%87%E5%8C%97#%E6%96%9C%E4%BD%93%E6%96%87%E5%AD%97%E4%BD%BF%E7%94%A8%E5%8A%A0%E7%B2%97%E6%A0%B7%E5%BC%8F%E4%BB%A3%E6%9B%BF)

2017-09-13 14:56 UTC, sqrthree commented on 2-ui/2-events/01-introduction-browser-events/article.md
> +** CSS事件：**
![image](https://user-images.githubusercontent.com/8622362/30383786-0b1da382-98d5-11e7-8776-b3e2cdfc721f.png)

2017-09-13 14:56 UTC, sqrthree commented on 2-ui/2-events/01-introduction-browser-events/article.md
> +事件处理函数可以设置在 HTML 元素的属性中，属性名称为`on <event>`。
『属性名称为`on <event>`』=>『属性名称为 `on<event>`』

调整了一下空格的位置。

2017-09-13 14:56 UTC, sqrthree commented on 2-ui/2-events/01-introduction-browser-events/article.md
> +例如，给`input`元素绑定一个`click`的事件处理器，我们可以使用`onclick`，如下所示：
[中英文之间需要增加空格](https://github.com/xitu/gold-miner/wiki/%E8%AF%91%E6%96%87%E6%8E%92%E7%89%88%E8%A7%84%E5%88%99%E6%8C%87%E5%8C%97#%E4%B8%AD%E8%8B%B1%E6%96%87%E4%B9%8B%E9%97%B4%E9%9C%80%E8%A6%81%E5%A2%9E%E5%8A%A0%E7%A9%BA%E6%A0%BC)

2017-09-13 14:56 UTC, sqrthree commented on 2-ui/2-events/01-introduction-browser-events/article.md
> +```html autorun height = 50
这个应该是网站 build 使用的标记吧，加空格的话会不会导致解析出错？

2017-09-13 14:56 UTC, sqrthree commented on 2-ui/2-events/01-introduction-browser-events/article.md
> +我们可以使用 DOM 属性`on <event>`来绑定一个事件处理器。
`on <event>` 问题同上

2017-09-13 14:56 UTC, sqrthree commented on 2-ui/2-events/01-introduction-browser-events/article.md
>  ```html run height=50 autorun
建议注释也翻译。

2017-09-13 14:56 UTC, sqrthree commented on 2-ui/2-events/01-introduction-browser-events/article.md
> +这样的赋值`elem.onclick = "alert(1)"`也可以被执行。但由于浏览器兼容性的原因，但不推荐这样使用。
『但由于浏览器兼容性的原因』=>『这是由于浏览器兼容性的原因』

2017-09-13 14:56 UTC, sqrthree commented on 2-ui/2-events/01-introduction-browser-events/article.md
> +** DOM 属性事件。**
![image](https://user-images.githubusercontent.com/8622362/30384207-41b5db3e-98d6-11e7-839f-b90a89aa30bb.png)

2017-09-13 14:56 UTC, sqrthree commented on 2-ui/2-events/01-introduction-browser-events/article.md
>  ````warn header="Removal requires the same function"
『Removal requires the same function』没有翻译

2017-09-13 14:56 UTC, sqrthree commented on 2-ui/2-events/01-introduction-browser-events/article.md
> +试着执行下面的代码。在大多数浏览器中，只有第二段代码会正常执行，而第一端不能。
『第一端』=>『第一段』

2017-09-13 14:56 UTC, sqrthree commented on 2-ui/2-events/01-introduction-browser-events/article.md
> +还有很多的属性。它们依赖于事件类型，所以我们稍后在详细介绍不同的事件时，再来学习。
『所以我们稍后在详细介绍不同的事件时，再来学习。』=>『所以我们稍后在详细介绍不同的事件时再来学习。』

2017-09-13 14:56 UTC, sqrthree commented on 2-ui/2-events/01-introduction-browser-events/article.md
>  ````smart header="The event object is also accessible from HTML"
『The event object is also accessible from HTML』也翻译一下吧。

2017-09-15 02:37 UTC, edward9145 commented on 2-ui/2-events/01-introduction-browser-events/article.md
>  ```html run height=50 autorun
这里下面的注释我也翻译了一下,在L122, L123

2017-09-15 02:43 UTC, edward9145 commented
I updated the translation. Please take a review again. @sqrthree

2017-09-18 01:35 UTC, linhe0x0 approved these changes
LGTM

2017-09-18 01:36 UTC, merged

2017-09-18 02:33 UTC, wizardforcel commented
`## 事件对象`一节上面少了个代码块的闭合，格式乱了。

2017-09-18 04:32 UTC, edward9145 commented
@wizardforcel 
这里和原文的markdown格式一致的，应该只是github的markdown解析不了326行的````造成的。

原文在github上也是乱的
https://github.com/iliakan/javascript-tutorial/blob/en/2-ui/2-events/01-introduction-browser-events/article.md

网站后台用的markdown解析应该是OK的